INSERT INTO Animal (name, picture, origin, description, youtube) VALUES ('Sumatran Tiger', 'https://ucarecdn.com/97d1d8c5-a4da-4baf-bd8c-1262c9fe4270/tiger240x240_btn.jpg', 'Asia', 'Sumatran tigers live in the forests of the island of Sumatra in Indonesia. They are the smallest kinds of tigers in the world, and there are only about 400 left in the wild.  They like to eat deers, pigs, birds, and fish.', 'https://www.youtube.com/watch?v=tYiUs7EvzoA');

INSERT INTO Animal (name, picture, origin, description, youtube) VALUES ('African Lion', 'https://ucarecdn.com/be3b736b-d48c-42e4-8658-8636d92adff9/lion240x240_btn.jpg', 'Africa', 'Lions are very big cats that like to live in groups as big as 30 lions! The female lions hunt the food for the group. The male lion is known as the “king of the jungle;” his job is to protect the place where they live and to defend the group from its enemies. Lions eat meat and they can sleep as much as 21 hours a day.', 'https://www.youtube.com/watch?v=Pdtau4LWjqI');

INSERT INTO Animal (name, picture, origin, description, youtube) VALUES ('Western Lowland Gorilla', 'https://ucarecdn.com/0589c835-11d5-4d83-bb65-52ba3a23b781/gorilla240x240_btn.jpg', 'Africa', 'Gorillas live in large groups that can have as many as 21 members. The group has one male leader and he decides when everybody sleeps and eats. He also takes care of the young gorillas and protects the group.', 'https://www.youtube.com/watch?v=aT3z9069i3Q');

INSERT INTO Animal (name, picture, origin, description, youtube) VALUES ('Eyelash Viper', 'https://ucarecdn.com/67155bae-6303-44b4-9741-b65eee1cd152/viper240x240_btn.jpg', 'Central and South America', 'The eyelid vipers live in the tropical rainforest, in trees near rivers and streams. They can be of many colors, but yellow and green are the most common. They have large scales on top of their eyes that look like eyelashes. Eyelid vipers are very active at night, and they eat small animals like frogs, lizards and mice.', 'https://www.youtube.com/watch?v=mr9-rjQNK34');

INSERT INTO Animal (name, picture, origin, description, youtube) VALUES ('Koala', 'https://ucarecdn.com/31716794-a820-474e-a229-596da29958a9/koala240x240_btn.jpg', 'Australia', 'Koalas live in eucalyptus forests, and eat eucalyptus leaves. Because they don’t have a lot of energy, they can sleep or rest for 20 hours each day. The baby koalas spend the first 6 months of their lives growing inside a pouch or pocket in their mother’s belly.', 'https://www.youtube.com/watch?v=zsKJKW-zeC0');

INSERT INTO Animal (name, picture, origin, description, youtube) VALUES ('American alligator', 'https://ucarecdn.com/059930d4-cf75-4575-a221-13945271aff9/alligator240x240_btn.jpg', 'North America', 'Alligators are very large and powerful reptiles that live in swamps, streams, rivers, ponds, and lakes. They like to eat other small animals like fish, birds, frogs, and mammals. Alligators build nests in sheltered spots near the water, where they lay up to 50 eggs!.', 'https://www.youtube.com/watch?v=qQTYf169dO4');